### ISSUE TITLE
Allow expenses that are limited to one roommate

### ISSUE THREAD

**Issue by KyNorthstar** [Supuhstar/Rent-Split-Calculator#6]
Doesn't have to be one, just less than the total. So like:

- Alex, Bri, and Chris share an apartment (for the sake of simplicity, say they all make the same salary)
- Bri has a dog
- The complex charges a $10/month pet fee
- Alex and Chris don't want to pay this fee since they don't own the pet
- **Bri will be the only one paying the extra $10**

Or this:

- Bri and Chris share a car
- The complex charges a monthly $50 parking fee (it's in a big city)
- Alex doesn't want to pay this fee since they don't own or drive the car
- **Bri and Chris will split this fee each month, each paying $25**

## Requirements: ##

- [x] #6.1 UI to specify which roommates contribute to an expense
    - [x] #6.1.1 UI to show when an expense does not apply to all roommates
    - [x] #6.1.2 UI to easily reset this filter
    - [x] #6.1.3 UI must not allow an expense to apply to no one
- [x] #6.2 Mobile support
    - [x] #6.2.1 A replacement for hover effects
- [x] #6.3 Saved in local storage
    - [x] #6.3.1 Loaded from local storage
- [x] #6.4 Totals must reflect this filter
    - [x] #6.4.1 If an expense applies to no one, it must show something that is not a dollar amount
    - [x] #6.4.2 If all expenses apply to everyone, totals must behave the same as before this feature
    - [x] #6.4.3 If an expense applies to some roommates, it must be split proportionally among only those, with the others seeing none of it

**Comment by BenLeggiero** [comment]
### Requirements:

- [ ] #6.1 UI to specify which roommates contribute to an expense
    - [ ] #6.1.1 UI to show when an expense does not apply to all roommates
    - [ ] #6.1.2 UI to easily reset this filter
- [ ] #6.2 Mobile support
    - [ ] #6.2.1 A replacement for hover effects
- [ ] #6.3 Saved in local storage
    - [ ] #6.3.1 Loaded from local storage
